### ISSUE TITLE
No module named 'src.model.mlp_dynamic'

### ISSUE THREAD

**Issue by hrzhou2** [tianfr/Semantic-Flow#1]
Hi, I run into an error when training the model. It says no such a module named `src.model.mlp_dynamic`:

```
Traceback (most recent call last):
  File "train/train_ddp_sceneflow_semantic.py", line 18, in <module>
    import trainlib
  File "/home/Work/code/Semantic-Flow/train/trainlib/__init__.py", line 1, in <module>
    from .trainer import Trainer
  File "/home/Work/code/Semantic-Flow/train/trainlib/trainer.py", line 14, in <module>
    from src.model import make_model
  File "/home/Work/code/Semantic-Flow/src/model/__init__.py", line 1, in <module>
    from .models import SemanticFlowNet
  File "/home/Work/code/Semantic-Flow/src/model/models.py", line 17, in <module>
    from .model_util import make_encoder, make_mlp
  File "/home/Work/code/Semantic-Flow/src/model/model_util.py", line 11, in <module>
    from .mlp_dynamic import MLP_dynamic
ModuleNotFoundError: No module named 'src.model.mlp_dynamic'
```

I can't find this `mlp_dynamic` as well as another `mlp_static`. It seems they are some local modules under `src/model`?

Really appreciate your work. Could you please help?

**Comment by tianfr** [comment]
Hi,

Thank you for your feedback! 

You can simply delete related references about `mlp_dynamic` and `mlp_static`. These are vanilla NeRF models without residual connections and are not related to our work. I also updated this repo to repair this bug.

If you have further questions, feel free to let me know!
